server:
  port: 8090
spring:
  application:
   name: chat-bot-service

feign:
  client:
   config:
    default:
     connect-timeout: 5000
     read-timeout: 30000
     logger-level: full

groq:
  api-key: ${GROQ_API_KEY}
  base-url: https://api.groq.com/openai
  model: llama-3.3-70b-versatile
  temperature: 0.3
