spring:
  application:
    name: auth-service

server:
  port: 8091

user:
  service:
    url: http://localhost:8082

jwt:
  secret: "Z4m8Qw1rT9fA3dS6yL2uC7xV5pK0nH8J3wR6bT9fY2lP5vM8qR1sD4gT7hW0k"
  expiration-millis: 3600000
