server:
  port: 8085

spring:
  application:
    name: trip-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/tripdb

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
